
name: Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - run: |
        mkdir logs
        touch logs/test.txt
        wget https://www.7-zip.org/a/7z1900.msi
        cd logs
        wget https://download.xnview.com/XnViewMP-win.exe
     - name: Archivage des binaires de l'application
       uses: actions/upload-artifact@v2
       with: 
        path: 7z1900.msi # prend et zip un fichier particulier
        name: Release             # et l'upload en tant que Release.zip
     - name: Archivage des logs techniques
       uses: actions/upload-artifact@v2
       with:
        path: logs               # prend tous les fichiers du dossier logs
        name: logs                # et les upload dans un fichier logs.zip
