name: concurrency

on:
  workflow_dispatch:

jobs:
  build:
    concurrency: test
    runs-on: ubuntu-latest

    steps:
     - run: echo hello
     - name: Wait / Sleep
       uses: jakejarvis/wait-action@v0.1.0
       with:
        time: '30s'
     - run: echo hello
     
