name: jobs - exercice 2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          dayOfWeek=$(date +%u)
          if($dayOfWeek>5)
          then
            exit 1
          fi
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()
    steps:
      - run: echo job2
  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: always()
    steps:
      - run: echo job3
