name: github-script

on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: set-result
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log("hello")
          return "Hello!"
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
    
    - uses: actions/github-script@v6
      id: get-repos
      with:
        github-token: ${{secrets.MY_GITHUB_TOKEN}}
        script: |
          return github.rest.repos.listForUser({
            username : "lgmorand"
          });
    - name: Get result
      run: echo "${{steps.get-repos.outputs.result}}";
    - uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "🎉 You've created this issue using GitHub Script!!!"
          })
