# This is a basic workflow to help you get started with Actions

name: Hello

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      MA_VARIABLE_PRENOM: Jean
      MA_VARIABLE_NOM: "Du pont"
      MA_VARIABLE_MULTILIGNE: |
                            bonjour
                            à tous
                            !

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "${{env.MA_VARIABLE_MULTILIGNE}}"
      - run: echo ${{GITHUB_HEAD_REF}}
      - run: echo ${{GITHUB_BASE_REF}}
      - uses: lgmorand/github-action-hello@v5
        with:
          prenom: 'Louis-Guillaume' 
          prenom2: 'toto'
