name: job-summary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Generate list using Markdown
       run: |
        echo "# This is a title" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- My first element" >> $GITHUB_STEP_SUMMARY
        echo "- My second one" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one with an icon :thumbsup:?" >> $GITHUB_STEP_SUMMARY


     
