name: latest release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: "Build Changelog"
       id: build_changelog
       uses: mikepenz/release-changelog-builder-action@{latest-release}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
