name: output

on:
  workflow_dispatch:
  
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
    - id: monStep
      run: echo "::set-output name=NOMVARIABLE::toto"
    - run: echo ${{ steps.monStep.outputs.NOMVARIABLE}}
    - id: monStep2
      run: echo "NOMVARIABLE=hello" >> $GITHUB_OUTPUT
    - run: echo **${{ steps.monStep2.outputs.NOMVARIABLE }}**
