name: release Asset
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - run: |
         echo 'totot' > CHANGELOG.txt
         echo 'totot' >  MonApplication.windows.x86.msi
         echo 'totot' >  MonApplication.windows.x64.msi
         echo 'totot' >  MonApplication.linux.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            CHANGELOG.txt
            MonApplication.windows.x86.msi
            MonApplication.windows.x64.msi
            MonApplication.linux.tar.gz
