name: Release Asset
on:
  workflow_dispatch:
  push:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
         touch release-notes.txt
         touch MonApplication.windows.x86.msi
         touch MonApplication.windows.x64.msi
         touch MonApplication.linux.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            MonApplication.windows.x86.msi
            MonApplication.windows.x64.msi
            MonApplication.linux.tgz
