name: relnotes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 100
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1
      with:
        toTag: 'v1.0.0'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
