name: secretWkf

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "${{ secrets.MON_SECRET }}"
    
    - run: echo "${{ secrets.MON_SECRET }}" | sed 's/./& /g'
    
    - run: echo "salut mon p@ssw0rd est visible"
   
