name: Units tests splitted
on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: echo rien
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-path: 
          - tests/integration/login/
          - tests/integration/orders/
          - tests/integration/basket/
          - tests/integration/other/
    steps:
      - name: Run integration tests
        run: sleep 25
  packing:
    runs-on: ubuntu-latest
    steps:
      - name: Create package
        run:  echo "test"
