name: Units tests
on:

  workflow_dispatch:

jobs:
  mon-project:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: sleep 117
      - name: Create package
        run:  echo "test"
