# This is a basic workflow to help you get started with Actions

name: var - scope

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      VARIABLE: yellow
    steps:
    - run: echo $VARIABLE  # displays "yellow", default value
    - run: |
        echo "VARIABLE=green" >> $GITHUB_ENV
        echo $VARIABLE     # displays "yellow", because we're still in the same step
    - run: echo $VARIABLE  # displays "green"
