name: variables-exercice 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: DD/MM/YYYY
        
    - run: echo ${{ steps.current-time.outputs.formattedTime }}
