
name: var - scope

on:
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      VARIABLE: yellow
    steps:
    - run: echo $VARIABLE  # displays "yellow", default value
    - run: |
        echo "VARIABLE=green" >> $GITHUB_ENV
        echo $VARIABLE     # displays "yellow", because we're still in the same step
    - run: echo $VARIABLE  # displays "green"
