name: workflow context values

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: My first command
      run: echo 'Execution of my command'
    - name: my second command
      run: echo 'Execution of my second command'
      
  build:
    runs-on: ubuntu-latest
    env:
      toto: tete
    
    steps:
    - name: Nom du workflow
      run: echo "${{ toJson(env) }}"
    - name: Nom du workflow
      run: echo ${{ github.workflow }} 
    - name: URL du profil du owner du repository
      run: echo ${{ github.event.repository.owner.html_url }} 
    - name: URL du profile du owner du repository
      run:  echo "::warning::Ce repository est public!"
      if: ${{ github.event.repository.private == 'false' }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "${GITHUB_CONTEXT}"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo ${MATRIX_CONTEXT}
